/**
 * Feeds-Overview UI layer.
 *
 * Sections of this file were generated by ChatGPT-Copilot assistance.
 */
package com.github.meeplemeet.ui.posts

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.Article
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Search
import androidx.compose.material.icons.outlined.ChatBubbleOutline
import androidx.compose.material.icons.outlined.MoreVert
import androidx.compose.material3.*
import androidx.compose.material3.HorizontalDivider
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.lifecycle.viewmodel.compose.viewModel
import com.github.meeplemeet.model.account.Account
import com.github.meeplemeet.model.account.RelationshipStatus
import com.github.meeplemeet.model.posts.Post
import com.github.meeplemeet.model.posts.PostOverviewViewModel
import com.github.meeplemeet.ui.navigation.BottomBarWithVerification
import com.github.meeplemeet.ui.navigation.MeepleMeetScreen
import com.github.meeplemeet.ui.navigation.NavigationActions
import com.github.meeplemeet.ui.navigation.NavigationTestTags
import com.github.meeplemeet.ui.theme.AppColors
import com.github.meeplemeet.ui.theme.Dimensions
import com.github.meeplemeet.ui.theme.MessagingColors
import java.text.SimpleDateFormat
import java.util.*

object FeedsOverviewTestTags {
  const val ADD_POST_BUTTON = "AddPostButton"
  const val POST_CARD_PREFIX = "Post/"
  const val SEARCH_TEXT_FIELD = "PostSearchTextField"
  const val SEARCH_CLEAR = "PostSearchClear"
}

object PostOverviewScreenUi {
  val xxxLargePadding = Dimensions.Padding.xxxLarge
}

/* ==========  CONSTANTS  ====================================================== */
/** Placeholder text shown when the feed contains zero posts. */
private const val NO_POSTS_DEFAULT_TEXT = "No Posts yet"

/* ==========  PUBLIC API  ===================================================== */
/**
 * Root screen that displays a scrollable list of posts (the “feed”).
 *
 * Observes [PostOverviewViewModel.posts] and re-composes whenever the list changes. Posts are
 * sorted newest-first.
 *
 * @param viewModel ViewModel that supplies the list of posts.
 * @param navigation Actions for navigation events.
 * @param onClickAddPost Callback fired when the FAB is tapped.
 * @param onSelectPost Callback fired when a post card is tapped.
 * @param account The currently logged in account
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PostsOverviewScreen(
    verified: Boolean,
    navigation: NavigationActions,
    viewModel: PostOverviewViewModel = viewModel(),
    account: Account,
    onClickAddPost: () -> Unit = {},
    onSelectPost: (Post) -> Unit = {},
) {
  val context = LocalContext.current
  val posts by viewModel.posts.collectAsState()

  var searchQuery by rememberSaveable { mutableStateOf("") }

  val postsSorted =
      remember(posts, searchQuery) {
        val sorted = posts.sortedByDescending { it.timestamp }

        // Filter by search query
        if (searchQuery.isBlank()) {
          sorted
        } else {
          val query = searchQuery.trim().lowercase()
          sorted.filter { post -> post.title.lowercase().contains(query) }
        }
      }

  Scaffold(
      floatingActionButton = {
        if (verified)
            FloatingActionButton(
                onClick = onClickAddPost,
                modifier = Modifier.testTag(FeedsOverviewTestTags.ADD_POST_BUTTON),
                containerColor = MessagingColors.redditOrange,
                contentColor = MessagingColors.messagingSurface,
                shape = CircleShape) {
                  Icon(
                      Icons.Default.Add,
                      contentDescription = "Create",
                      modifier = Modifier.size(Dimensions.IconSize.large))
                }
      },
      topBar = {
        Column(Modifier.fillMaxWidth()) {
          CenterAlignedTopAppBar(
              colors =
                  TopAppBarDefaults.topAppBarColors(
                      containerColor = MaterialTheme.colorScheme.surface),
              title = {
                Text(
                    text = MeepleMeetScreen.PostsOverview.title,
                    style = MaterialTheme.typography.titleLarge,
                    fontSize = Dimensions.TextSize.largeHeading,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.onSurface,
                    modifier = Modifier.testTag(NavigationTestTags.SCREEN_TITLE))
              })
          PostSearchBar(
              query = searchQuery,
              onQueryChange = { searchQuery = it },
              onClearQuery = { searchQuery = "" })
        }
      },
      bottomBar = {
        BottomBarWithVerification(
            currentScreen = MeepleMeetScreen.PostsOverview,
            onTabSelected = { screen -> navigation.navigateTo(screen) },
            verified = verified,
            onVerifyClick = { navigation.navigateTo(MeepleMeetScreen.Profile) })
      }) { innerPadding ->
        if (postsSorted.isEmpty()) {
          Box(modifier = Modifier.fillMaxSize().padding(innerPadding)) { EmptyFeedListText() }
        } else {
          LazyColumn(
              modifier = Modifier.fillMaxSize().padding(innerPadding),
              verticalArrangement = Arrangement.spacedBy(Dimensions.Spacing.none)) {
                items(postsSorted, key = { it.id }) { post ->
                  if (account.relationships[post.authorId] == RelationshipStatus.BLOCKED)
                      return@items

                  val dateFormatted =
                      SimpleDateFormat("dd/MM/yyyy", Locale.getDefault())
                          .format(post.timestamp.toDate())

                  val authorName by
                      produceState<String?>(key1 = post.authorId, initialValue = null) {
                        viewModel.getAccount(post.authorId, context) { acc ->
                          value = acc?.name ?: "Unknown"
                        }
                      }

                  FeedCard(
                      authorName = authorName ?: post.authorId,
                      postTitle = post.title,
                      commentCount = post.commentCount,
                      date = dateFormatted,
                      firstTag = post.tags.firstOrNull(),
                      modifier =
                          Modifier.fillMaxWidth()
                              .testTag(FeedsOverviewTestTags.POST_CARD_PREFIX + post.id),
                      onClick = { onSelectPost(post) })
                }
              }
        }
      }
}

/* ==========  EMPTY STATE  ==================================================== */
/** Displays a centred label when the feed contains no posts. */
@Composable
private fun EmptyFeedListText() {
  Box(
      modifier = Modifier.fillMaxSize().padding(PostOverviewScreenUi.xxxLargePadding),
      contentAlignment = Alignment.Center) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(Dimensions.Spacing.medium)) {
              Icon(
                  imageVector = Icons.AutoMirrored.Filled.Article,
                  contentDescription = null,
                  modifier = Modifier.size(Dimensions.IconSize.giant),
                  tint = MessagingColors.secondaryText)
              Spacer(modifier = Modifier.height(Dimensions.Spacing.medium))
              Text(
                  text = NO_POSTS_DEFAULT_TEXT,
                  style = MaterialTheme.typography.bodyLarge,
                  fontSize = Dimensions.TextSize.title,
                  color = MessagingColors.secondaryText)
            }
      }
}

/* ==========  FEED CARD  ====================================================== */
/**
 * Visual representation of a single post in the feed (Reddit-style).
 *
 * Layout: Horizontal card with icon on left, content in middle, compact metadata
 *
 * @param authorName Display name of the post creator.
 * @param postTitle Title of the post.
 * @param commentCount Total number of comments on the post.
 * @param date Post creation date formatted as dd/MM/yyyy.
 * @param firstTag First tag of the post (nullable). Shown as a flair badge.
 * @param modifier Optional [Modifier].
 * @param onClick Callback invoked when the card is tapped.
 */
@Composable
public fun FeedCard(
    authorName: String,
    postTitle: String,
    commentCount: Int,
    date: String,
    firstTag: String?,
    modifier: Modifier = Modifier,
    onClick: () -> Unit = {}
) {
  Column(modifier = modifier) {
    Row(
        modifier =
            Modifier.fillMaxWidth()
                .clickable(onClick = onClick)
                .background(MessagingColors.messagingSurface)
                .padding(
                    horizontal = Dimensions.Spacing.large, vertical = Dimensions.Spacing.large),
        horizontalArrangement = Arrangement.spacedBy(Dimensions.Spacing.large)) {
          // Left icon/thumbnail
          Box(
              modifier =
                  Modifier.size(Dimensions.AvatarSize.large)
                      .clip(RoundedCornerShape(Dimensions.CornerRadius.medium))
                      .background(MessagingColors.messagingBackground),
              contentAlignment = Alignment.Center) {
                Icon(
                    imageVector = Icons.AutoMirrored.Filled.Article,
                    contentDescription = null,
                    modifier = Modifier.size(Dimensions.IconSize.large),
                    tint = MessagingColors.secondaryText)
              }

          // Content column
          Column(
              modifier = Modifier.weight(1f),
              verticalArrangement = Arrangement.spacedBy(Dimensions.Spacing.small)) {
                // Tag/Flair badge
                if (!firstTag.isNullOrBlank()) {
                  Row(verticalAlignment = Alignment.CenterVertically) {
                    Surface(
                        shape = RoundedCornerShape(Dimensions.CornerRadius.small),
                        color = MessagingColors.redditBlueBg,
                        modifier = Modifier.height(Dimensions.IconSize.standard)) {
                          Text(
                              text = firstTag,
                              style = MaterialTheme.typography.labelSmall,
                              fontSize = Dimensions.TextSize.tiny,
                              fontWeight = FontWeight.Bold,
                              color = MessagingColors.redditBlue,
                              modifier =
                                  Modifier.padding(
                                      horizontal = Dimensions.Spacing.small,
                                      vertical = Dimensions.Spacing.extraSmall),
                              maxLines = 1,
                              overflow = TextOverflow.Ellipsis)
                        }
                  }
                }

                // Title
                Text(
                    text = postTitle,
                    style = MaterialTheme.typography.titleMedium,
                    fontSize = Dimensions.TextSize.subtitle,
                    fontWeight = FontWeight.Medium,
                    color = MessagingColors.primaryText,
                    maxLines = 2,
                    overflow = TextOverflow.Ellipsis)

                // Metadata row (author, date, comments)
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(Dimensions.Spacing.small)) {
                      // Author
                      Text(
                          text = authorName,
                          style = MaterialTheme.typography.bodySmall,
                          fontSize = Dimensions.TextSize.small,
                          color = MessagingColors.secondaryText,
                          maxLines = 1,
                          overflow = TextOverflow.Ellipsis,
                          modifier = Modifier.weight(1f, fill = false))

                      Text(
                          text = "•",
                          fontSize = Dimensions.TextSize.small,
                          color = MessagingColors.secondaryText)

                      // Date
                      Text(
                          text = date,
                          style = MaterialTheme.typography.bodySmall,
                          fontSize = Dimensions.TextSize.small,
                          color = MessagingColors.secondaryText)
                    }

                // Comments row
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(Dimensions.Spacing.small)) {
                      Icon(
                          imageVector = Icons.Outlined.ChatBubbleOutline,
                          contentDescription = "comments",
                          modifier = Modifier.size(Dimensions.IconSize.small),
                          tint = MessagingColors.secondaryText)
                      Text(
                          text = "$commentCount comments",
                          style = MaterialTheme.typography.bodySmall,
                          fontSize = Dimensions.TextSize.small,
                          fontWeight = FontWeight.Medium,
                          color = MessagingColors.secondaryText)
                    }
              }

          // More options icon
          IconButton(
              onClick = { /* TODO: Show options */},
              modifier = Modifier.size(Dimensions.IconSize.large)) {
                Icon(
                    imageVector = Icons.Outlined.MoreVert,
                    contentDescription = "More options",
                    tint = MessagingColors.secondaryText,
                    modifier = Modifier.size(Dimensions.IconSize.standard))
              }
        }

    // Divider
    HorizontalDivider(
        color = MessagingColors.divider, thickness = Dimensions.DividerThickness.standard)
  }
}

/**
 * Composable function for the post search bar.
 *
 * @param query The current search query.
 * @param onQueryChange Callback when the search query changes.
 * @param onClearQuery Callback to clear the search query.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun PostSearchBar(
    query: String,
    onQueryChange: (String) -> Unit,
    onClearQuery: () -> Unit
) {
  TextField(
      value = query,
      onValueChange = onQueryChange,
      modifier =
          Modifier.fillMaxWidth()
              .height(Dimensions.ContainerSize.timeFieldHeight)
              .testTag(FeedsOverviewTestTags.SEARCH_TEXT_FIELD),
      placeholder = {
        Text(
            "Search posts...",
            style = MaterialTheme.typography.bodyMedium,
        )
      },
      singleLine = true,
      leadingIcon = {
        Icon(
            imageVector = Icons.Default.Search,
            contentDescription = "Search",
        )
      },
      trailingIcon = {
        if (query.isNotEmpty()) {
          IconButton(
              onClick = onClearQuery,
              modifier = Modifier.testTag(FeedsOverviewTestTags.SEARCH_CLEAR),
          ) {
            Icon(
                imageVector = Icons.Default.Close,
                contentDescription = "Clear search",
            )
          }
        }
      },
      textStyle = MaterialTheme.typography.bodyMedium,
      colors =
          TextFieldDefaults.colors(
              focusedTextColor = AppColors.textIcons,
              unfocusedTextColor = AppColors.textIcons,
              focusedContainerColor = AppColors.divider,
              unfocusedContainerColor = AppColors.divider,
              disabledContainerColor = AppColors.divider,
              focusedIndicatorColor = Color.Transparent,
              unfocusedIndicatorColor = Color.Transparent,
              disabledIndicatorColor = Color.Transparent,
          ),
  )
}
