#!/usr/bin/env bash

# Script to detect repeated string literals in the com.github.meeplemeet package
# Repeated strings should be extracted as constants for maintainability

# Generated by Claude Code

set -e

PACKAGE_DIR="app/src/main/java/com/github/meeplemeet"
ERRORS=0
MIN_STRING_LENGTH=3
MIN_OCCURRENCES=3

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "🔍 Checking for repeated string literals in com.github.meeplemeet package..."
echo ""

# Patterns to exclude from checking
EXCLUDE_FILES=(
  # Test files often have repeated strings
  "test/"
  "androidTest/"
  # Theme/constants files are allowed to have repeated values
  "ui/theme/"
)

# Common strings to ignore (these are acceptable to repeat)
IGNORE_STRINGS=(
  # Common UI strings
  '""'
  '" "'
  '","'
  '": "'
  '","'
  '"/"'
  '"-"'
  '"_"'
  '"."'
  '"="'
  '"@"'
  '"#"'
  '"$"'
  '"%"'
  '"&"'
  '"*"'
  '"+"'
  '"<"'
  '">"'
  '"("'
  '")"'
  '"["'
  '"]"'
  '"{"'
  '"}"'
  '"||"'
  '"&&"'
  '"\n"'
  '"\t"'
  # Common navigation/tags
  '"Back"'
  '"Error"'
  '"Success"'
  '"Loading"'
  '"OK"'
  '"Cancel"'
  '"Pick"'
  # Common attribute names
  '"id"'
  '"name"'
  '"type"'
  '"value"'
  '"key"'
  '"data"'
  '"text"'
  '"title"'
  '"description"'
  '"icon"'
  '"image"'
  '"url"'
  # Common test description words
  '"should"'
  '"when"'
  '"then"'
  '"given"'
  '"and"'
  '"or"'
  '"not"'
  '"is"'
  '"are"'
  '"has"'
  '"have"'
)

# Function to check if file should be excluded
should_exclude() {
  local file=$1
  for exclude in "${EXCLUDE_FILES[@]}"; do
    if [[ "$file" == *"$exclude"* ]]; then
      return 0
    fi
  done
  return 1
}

# Function to check if string should be ignored
should_ignore_string() {
  local string=$1
  for ignore in "${IGNORE_STRINGS[@]}"; do
    if [[ "$string" == "$ignore" ]]; then
      return 0
    fi
  done
  return 1
}

# Check if package directory exists
if [ ! -d "$PACKAGE_DIR" ]; then
  echo -e "${RED}Error: Package directory not found: $PACKAGE_DIR${NC}"
  exit 1
fi

# Create a temporary file to store results
TEMP_FILE=$(mktemp)
trap 'rm -f "$TEMP_FILE"' EXIT

# Find all Kotlin files in package directory
while IFS= read -r file; do
  # Skip excluded files
  if should_exclude "$file"; then
    continue
  fi

  # Extract all string literals from the file (strings with 3+ chars)
  # This regex matches strings in double quotes, excluding single/empty strings
  strings=$(grep -oE '"[^"]{'"$MIN_STRING_LENGTH"',}"' "$file" 2>/dev/null || true)

  if [ -z "$strings" ]; then
    continue
  fi

  # Get unique strings and count occurrences
  while IFS= read -r string; do
    if [ -n "$string" ] && ! should_ignore_string "$string"; then
      # Count how many times this string appears in the file
      count=$(grep -oF "$string" "$file" 2>/dev/null | wc -l | tr -d ' ')

      # Only record if it appears MIN_OCCURRENCES or more times
      if [ "$count" -ge "$MIN_OCCURRENCES" ]; then
        # Check if we've already recorded this string for this file
        if ! grep -qF "$file|$string|" "$TEMP_FILE" 2>/dev/null; then
          echo "$file|$string|$count" >> "$TEMP_FILE"
        fi
      fi
    fi
  done <<< "$(echo "$strings" | sort -u)"
done < <(find "$PACKAGE_DIR" -name "*.kt" -type f)

# Display results
if [ -s "$TEMP_FILE" ]; then
  while IFS='|' read -r file string count; do
    if [ $ERRORS -eq 0 ]; then
      echo -e "${BLUE}Files with repeated string literals (${MIN_OCCURRENCES}+ occurrences):${NC}"
      echo ""
    fi

    echo -e "${RED}✗ Repeated string in: ${file#*/}${NC}"
    echo -e "  ${YELLOW}String: $string appears $count times${NC}"

    # Show the line numbers where this string appears
    lines=$(grep -n "$string" "$file" 2>/dev/null | head -5 | cut -d: -f1 | tr '\n' ',' | sed 's/,$//')
    if [ -n "$lines" ]; then
      echo -e "  ${BLUE}Lines: $lines${NC}"
    fi
    echo ""

    ERRORS=$((ERRORS + 1))
  done < "$TEMP_FILE"
fi

# Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ $ERRORS -eq 0 ]; then
  echo -e "${GREEN}✓ No repeated string literals detected!${NC}"
  exit 0
else
  echo -e "${RED}✗ Found repeated strings in $ERRORS file(s)${NC}"
  echo ""
  echo "Repeated string literals should be extracted as constants."
  echo ""
  echo "Example:"
  echo '  ❌ Text("Welcome"), Text("Welcome"), Text("Welcome")'
  echo '  ✅ private const val WELCOME_TEXT = "Welcome"'
  echo '     Text(WELCOME_TEXT), Text(WELCOME_TEXT), Text(WELCOME_TEXT)'
  echo ""
  echo "Consider creating a constants object or companion object in the file."
  exit 1
fi
