#!/bin/bash

# Script to detect magic numbers in the UI package
# Magic numbers are numeric literals (except 0, 1, -1) that appear directly in code
# instead of being defined as named constants

# Generated by Claude Code

set -e

UI_DIR="app/src/main/java/com/github/meeplemeet/ui"
ERRORS=0

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "🔍 Checking for magic numbers in UI package..."
echo ""

# Patterns to exclude:
# - Theme files (they define constants)
# - Dimension files (they define constants)
# - Color files (they define color values)
# - Type files (they define typography)
EXCLUDE_FILES=(
  "theme/AppColors.kt"
  "theme/Color.kt"
  "theme/Dimensions.kt"
  "theme/Elevation.kt"
  "theme/Type.kt"
  "theme/Shape.kt"
  "theme/Theme.kt"
  "theme/MessagingColors.kt"
)

# Function to check if file should be excluded
should_exclude() {
  local file=$1
  for exclude in "${EXCLUDE_FILES[@]}"; do
    if [[ "$file" == *"$exclude"* ]]; then
      return 0
    fi
  done
  return 1
}

# Find all Kotlin files in UI directory
if [ ! -d "$UI_DIR" ]; then
  echo -e "${RED}Error: UI directory not found: $UI_DIR${NC}"
  exit 1
fi

# Search for magic numbers in UI files
# Pattern explanation:
# - Look for numeric literals that are not 0, 1, or -1
# - Exclude hex colors (0x...)
# - Exclude floats like 0.5f, 1.0f
# - Check common UI contexts: padding, size, offset, weight, etc.

while IFS= read -r file; do
  # Skip excluded files
  if should_exclude "$file"; then
    continue
  fi

  # Check for suspicious numeric patterns
  # Look for: numbers >= 2 or <= -2, and common decimal values
  # Exclude lines that are constant declarations (val NAME = NUMBER.dp/sp)
  matches=$(grep -nE '\b([2-9]|[1-9][0-9]+)(\.[0-9]+)?[fF]?\s*(\.dp|\.sp)' "$file" 2>/dev/null | grep -vE '^\s*[0-9]+:\s*(private\s+)?val\s+[A-Z_][A-Z0-9_]*\s*(:.*?)?\s*=\s*[0-9.]+\s*\.(dp|sp)' || true)

  if [ -n "$matches" ]; then
    echo -e "${RED}✗ Magic numbers found in: ${file#*/}${NC}"
    echo "$matches" | while read -r line; do
      echo -e "  ${YELLOW}Line: $line${NC}"
    done
    echo ""
    ERRORS=$((ERRORS + 1))
  fi
done < <(find "$UI_DIR" -name "*.kt" -type f)

# Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ $ERRORS -eq 0 ]; then
  echo -e "${GREEN}✓ No magic numbers detected!${NC}"
  exit 0
else
  echo -e "${RED}✗ Found magic numbers in $ERRORS file(s)${NC}"
  echo ""
  echo "Magic numbers should be replaced with named constants from:"
  echo "  - ui/theme/Dimensions.kt for sizes, padding, spacing"
  echo "  - ui/theme/Elevation.kt for elevation values"
  echo ""
  echo "Example:"
  echo "  ❌ Modifier.padding(16.dp)"
  echo "  ✅ Modifier.padding(AppDimensions.paddingMedium)"
  exit 1
fi
